FROM ubuntu:24.04
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:gnucash/ppa && \
    apt-get update && \
    apt-get install -y python3-gnucash
