# Stub for the GnuCash Python bindings (python3-gnucash / SWIG-generated).
# Only the symbols used in this project are fully typed; the rest are Any.

from pathlib import Path
from typing import Any

# ── Error constants ───────────────────────────────────────────────────────────
ERR_BACKEND_LOCKED: int
ERR_FILEIO_FILE_NOT_FOUND: int

# ── Exceptions ────────────────────────────────────────────────────────────────
class GnuCashBackendException(Exception):
    errors: list[Any]
    def __init__(self, msg: str, errors: list[Any] = ...) -> None: ...

# ── SessionOpenMode ───────────────────────────────────────────────────────────
class SessionOpenMode(int):
    SESSION_NORMAL_OPEN: SessionOpenMode
    SESSION_NEW_STORE: SessionOpenMode
    SESSION_NEW_OVERWRITE: SessionOpenMode
    SESSION_READ_ONLY: SessionOpenMode
    SESSION_BREAK_LOCK: SessionOpenMode

SESSION_NORMAL_OPEN: SessionOpenMode
SESSION_NEW_STORE: SessionOpenMode
SESSION_NEW_OVERWRITE: SessionOpenMode
SESSION_READ_ONLY: SessionOpenMode
SESSION_BREAK_LOCK: SessionOpenMode

# ── GncNumeric ────────────────────────────────────────────────────────────────
class GncNumeric:
    def __init__(self, num: int = 0, denom: int = 1) -> None: ...
    def num(self) -> int: ...
    def denom(self) -> int: ...
    def to_double(self) -> float: ...
    def to_string(self) -> str: ...
    def zero_p(self) -> bool: ...
    def positive_p(self) -> bool: ...
    def negative_p(self) -> bool: ...
    def neg(self) -> GncNumeric: ...
    def abs(self) -> GncNumeric: ...
    def add(self, b: GncNumeric, denom: int, how: int) -> GncNumeric: ...
    def sub(self, b: GncNumeric, denom: int, how: int) -> GncNumeric: ...
    def mul(self, b: GncNumeric, denom: int, how: int) -> GncNumeric: ...
    def div(self, b: GncNumeric, denom: int, how: int) -> GncNumeric: ...
    def __add__(self, other: GncNumeric) -> GncNumeric: ...
    def __sub__(self, other: GncNumeric) -> GncNumeric: ...
    def __mul__(self, other: GncNumeric) -> GncNumeric: ...
    def __truediv__(self, other: GncNumeric) -> GncNumeric: ...
    def __neg__(self) -> GncNumeric: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: GncNumeric) -> bool: ...
    def __le__(self, other: GncNumeric) -> bool: ...
    def __gt__(self, other: GncNumeric) -> bool: ...
    def __ge__(self, other: GncNumeric) -> bool: ...

# ── GUID ──────────────────────────────────────────────────────────────────────
class GUID:
    def to_string(self) -> str: ...
    def equal(self, other: GUID) -> bool: ...

# ── GncCommodity ──────────────────────────────────────────────────────────────
class GncCommodity:
    def get_mnemonic(self) -> str: ...
    def get_fullname(self) -> str: ...
    def get_namespace(self) -> str: ...

# ── GncCommodityTable ─────────────────────────────────────────────────────────
class GncCommodityTable:
    def lookup(self, namespace: str, mnemonic: str) -> GncCommodity: ...
    def get_namespaces(self) -> list[Any]: ...

# ── Book ──────────────────────────────────────────────────────────────────────
class Book:
    def get_root_account(self) -> Account: ...
    def get_table(self) -> GncCommodityTable: ...
    def session_not_saved(self) -> bool: ...
    def shutting_down(self) -> bool: ...

# ── Account ───────────────────────────────────────────────────────────────────
class Account:
    def __init__(self, book: Book) -> None: ...
    def SetName(self, name: str) -> None: ...
    def SetType(self, acct_type: int) -> None: ...
    def SetCommodity(self, commodity: GncCommodity) -> None: ...
    def SetDescription(self, description: str) -> None: ...
    def SetCode(self, code: str) -> None: ...
    def SetHidden(self, hidden: bool) -> None: ...
    def SetPlaceholder(self, placeholder: bool) -> None: ...
    def GetName(self) -> str: ...
    def GetType(self) -> int: ...
    def GetDescription(self) -> str: ...
    def GetBalance(self) -> GncNumeric: ...
    def GetClearedBalance(self) -> GncNumeric: ...
    def GetReconciledBalance(self) -> GncNumeric: ...
    def GetCommodity(self) -> GncCommodity: ...
    def GetGUID(self) -> GUID: ...
    def GetSplitList(self) -> list[Any]: ...
    def GetSplitsSize(self) -> int: ...
    def Destroy(self) -> None: ...
    def get_parent(self) -> Account: ...
    def get_children(self) -> list[Account]: ...
    def get_descendants(self) -> list[Account]: ...
    def get_full_name(self) -> str: ...
    def get_book(self) -> Book: ...
    def append_child(self, child: Account) -> None: ...
    def remove_child(self, child: Account) -> None: ...
    def n_children(self) -> int: ...
    def is_root(self) -> bool: ...
    @property
    def name(self) -> str: ...

# ── Transaction ───────────────────────────────────────────────────────────────
class Transaction:
    def __init__(self, book: Book) -> None: ...
    def BeginEdit(self) -> None: ...
    def CommitEdit(self) -> None: ...
    def RollbackEdit(self) -> None: ...
    def SetDescription(self, desc: str) -> None: ...
    def SetCurrency(self, commodity: GncCommodity) -> None: ...
    def SetNum(self, num: str) -> None: ...
    def SetNotes(self, notes: str) -> None: ...
    def GetDescription(self) -> str: ...
    def GetCurrency(self) -> GncCommodity: ...
    def SetDate(self, day: int, month: int, year: int) -> None: ...
    def GetDate(self) -> Any: ...
    def GetSplit(self, index: int) -> Split: ...
    def GetSplitList(self) -> list[Split]: ...
    def CountSplits(self) -> int: ...
    def GetGUID(self) -> GUID: ...
    def IsBalanced(self) -> bool: ...
    def SetSlot(self, key: str, value: str) -> None: ...
    def GetSlot(self, key: str) -> str | None: ...
    def Destroy(self) -> None: ...

# ── Split ─────────────────────────────────────────────────────────────────────
class Split:
    def __init__(self, book: Book) -> None: ...
    def SetParent(self, txn: Transaction) -> None: ...
    def SetAccount(self, account: Account) -> None: ...
    def SetAmount(self, amount: GncNumeric) -> None: ...
    def SetValue(self, value: GncNumeric) -> None: ...
    def SetMemo(self, memo: str) -> None: ...
    def SetAction(self, action: str) -> None: ...
    def GetAccount(self) -> Account: ...
    def GetAmount(self) -> GncNumeric: ...
    def GetValue(self) -> GncNumeric: ...
    def GetMemo(self) -> str: ...
    def GetParent(self) -> Transaction: ...
    def GetGUID(self) -> GUID: ...

# ── Session ───────────────────────────────────────────────────────────────────
class Session:
    book: Book
    def __init__(
        self,
        book_uri: str | None = None,
        mode: SessionOpenMode | None = None,
        instance: Any = None,
        book: Book | None = None,
    ) -> None: ...
    def __enter__(self) -> Session: ...
    def __exit__(self, *args: Any) -> None: ...
    def save(self, percentage_func: Any = None) -> None: ...
    def safe_save(self, percentage_func: Any = None) -> None: ...
    def end(self) -> None: ...
    def destroy(self) -> None: ...
    def get_file_path(self) -> str: ...
    def raise_backend_errors(self, *args: Any) -> None: ...
    def generate_errors(self) -> list[Any]: ...
    def pop_all_errors(self) -> list[Any]: ...

# ── Everything else ───────────────────────────────────────────────────────────
def __getattr__(name: str) -> Any: ...
