# Stub for the GnuCash SWIG-generated C extension module.
# Only symbols used in this project are declared; everything else is `Any`.

from typing import Any

# ── Account type constants ────────────────────────────────────────────────────
ACCT_TYPE_NONE: int
ACCT_TYPE_BANK: int
ACCT_TYPE_CASH: int
ACCT_TYPE_CREDIT: int
ACCT_TYPE_ASSET: int
ACCT_TYPE_LIABILITY: int
ACCT_TYPE_STOCK: int
ACCT_TYPE_MUTUAL: int
ACCT_TYPE_CURRENCY: int
ACCT_TYPE_INCOME: int
ACCT_TYPE_EXPENSE: int
ACCT_TYPE_EQUITY: int
ACCT_TYPE_RECEIVABLE: int
ACCT_TYPE_PAYABLE: int
ACCT_TYPE_ROOT: int
ACCT_TYPE_TRADING: int
ACCT_TYPE_CHECKING: int
ACCT_TYPE_SAVINGS: int
ACCT_TYPE_MONEYMRKT: int
ACCT_TYPE_CREDITLINE: int
ACCT_TYPE_INVALID: int
ACCT_TYPE_LAST: int

# ── Account functions ─────────────────────────────────────────────────────────
def xaccAccountGetTypeStr(account_type: int) -> str: ...
def xaccAccountGetName(account: Any) -> str: ...
def xaccAccountGetDescription(account: Any) -> str: ...
def xaccAccountGetType(account: Any) -> int: ...
def xaccAccountGetSplitList(account: Any) -> list[Any]: ...
def xaccAccountDestroy(account: Any) -> None: ...
def xaccMallocAccount(book: Any) -> Any: ...

# ── Transaction functions ─────────────────────────────────────────────────────
def xaccTransGetDescription(txn: Any) -> str: ...
def xaccTransGetDate(txn: Any) -> Any: ...
def xaccTransGetSplitList(txn: Any) -> list[Any]: ...
def xaccTransDestroy(txn: Any) -> None: ...

# ── Split functions ───────────────────────────────────────────────────────────
def xaccSplitGetAccount(split: Any) -> Any: ...
def xaccSplitGetAmount(split: Any) -> Any: ...
def xaccSplitGetValue(split: Any) -> Any: ...
def xaccSplitGetMemo(split: Any) -> str: ...

# ── Session / QOF functions ───────────────────────────────────────────────────
def qof_session_new(book: Any) -> Any: ...
def qof_session_begin(session: Any, uri: str, ignore_lock: bool, create: bool, force: bool) -> None: ...
def qof_session_load(session: Any, percentage: Any) -> None: ...
def qof_session_save(session: Any, percentage: Any) -> None: ...
def qof_session_safe_save(session: Any, percentage: Any) -> None: ...
def qof_session_end(session: Any) -> None: ...
def qof_session_destroy(session: Any) -> None: ...
def qof_session_get_book(session: Any) -> Any: ...
def qof_session_get_error(session: Any) -> int: ...
def qof_session_pop_error(session: Any) -> int: ...
def qof_session_get_file_path(session: Any) -> str: ...
def qof_session_get_url(session: Any) -> str: ...

# ── Book functions ────────────────────────────────────────────────────────────
def qof_book_new() -> Any: ...
def qof_book_session_not_saved(book: Any) -> bool: ...

# ── Everything else ───────────────────────────────────────────────────────────
def __getattr__(name: str) -> Any: ...
